### ISSUE TITLE
Find nearest with Polygons

### ISSUE THREAD

**Issue by milafrerichs** [Turfjs/turf-nearest#7]
Hello,

first of all thanks for turf. It's really cool. Awesome stuff you built with it and what can be built with it. 
I was trying to use it and found a use-case for our Open Data group. 
We have an API that returns GeoJSON Features with parking lots but these can be Points or Poylgons. I was trying to find the nearest parking lot by using turf but turns out only Points are supported. 

I found a way to find the nearest Point or Polygon using turf-point-on-surface.
What's your opinion on using point-on-surface to calculate the distance for a Polygon?
I know this only makes sense for small polygons. But for our use case it was just perfect.

https://github.com/milafrerichs/turf-nearest/tree/nearest-polygon

Thanks.

mila

**Comment by tmcw** [comment]
-> https://github.com/Turfjs/turf/issues/359
