### ISSUE TITLE
using geojson within `turf.point(geojson, options)` returns an array error

### ISSUE THREAD

**Issue by mapsam** [Turfjs/turf-nearest#8]
Is it possible to use existing geojson layers with `turf.point()`? Right now the documentation makes it seem like you can only use point arrays. Here's the error:

```
Uncaught Error: Coordinates must be an array
```

Thanks for the help!

**Comment by tcql** [comment]
`turf.point([lon, lat])` is just a shortcut for making the geojson feature

```
{
  "type": "Feature",
  "properties": {},
  "geometry": {
    "type": "Point", 
    "coordinates": [lon, lat]
  }
}
```

so if your feature is already in geojson, just don't wrap it in a `turf.point` call

**Comment by mapsam** [comment]
Oh wow. Thanks!

**Comment by blackgis** [comment]
I used pointOnLine and in the first case we loaded json files and the turf.point and turf.line was used successfully. Then we used geojson and it gave the same error as described here - using only the geometry property without the turf.point and turf.line, solved this issue.
